# docker compose -f docker-compose_crypto.yml --env-file ./compose.env up -d
# docker compose -f docker-compose_crypto.yml --env-file ./compose.env up -d telegram_crypto1
version: '3.9'

services:
  data_provider1:
    build:
      context: ../..
      dockerfile:  smartbot-python.dockerfile
    hostname: exchange_provider
    volumes:
      - ..:/app
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
    networks:
      - smartbots_networks
    command: python -u ./src/application/bots/crypto_trading/provider_crypto.py

  bot_crypto_trading1:
    build:
      context: ../..
      dockerfile: smartbot-python.dockerfile
    hostname: bot_crypto_trading1
    volumes:
      - ..:/app
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      ROUTING_KEY: crypto_order
    networks:
      - smartbots_networks
    command: python -u ./src/application/bots/portfolio_production.py

  broker_crypto1:
    build:
      context: ../..
      dockerfile: smartbot-python.dockerfile
    hostname: broker_crypto1
    volumes:
      - ..:/app
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      ROUTING_KEY: crypto_order
    networks:
      - smartbots_networks
    command: python -u ./src/application/bots/crypto_trading/broker_crypto.py

  telegram_crypto1:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: telegram_crypto1
    volumes:
      - ..:/app
    networks:
      - smartbots_networks
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      TRADING_TYPE_DOCKER: crypto
    command: python -u ./src/application/bots/telegram_bot.py

networks:
  smartbots_networks:
    ipam:
      config:
        - subnet: 172.20.0.0/24